main = ".open-next/worker.js"
name = "intuipay-website-dev"
compatibility_date = "2025-08-14" # Use a recent date
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

account_id = "07ee1a1a1cf0da549eaaf6d3c5c80b62"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB" # This is how you'll access it in your code
database_name = "waitlist"
database_id = "a8ec52c6-d6c9-455b-b8b0-55d2d4a007e2"

[[kv_namespaces]]
binding = "KV"
id = "f199722e3f7e4bdabd77a428770d7ed5"
preview_id = "14a383e6cf6f466ba8c535f0ab64d4ac"
