main = ".open-next/worker.js"
name = 'intuipay-website-staging'
compatibility_date = "2025-08-25" # Use a recent date
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

account_id = "07ee1a1a1cf0da549eaaf6d3c5c80b62"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB" # This is how you'll access it in your code
database_name = "dashboard"
database_id = "ce69bdf0-4220-43f9-b6dc-e5eaf27e4850"

[[kv_namespaces]]
binding = "KV"
id = "f199722e3f7e4bdabd77a428770d7ed5"
preview_id = "14a383e6cf6f466ba8c535f0ab64d4ac"

[observability.logs]
enabled = true

[vars]
TIDB_CLOUD_ENDPOINT = "https://ap-southeast-1.data.tidbcloud.com/api/v1beta/app/dataapp-qgvFPRfq/endpoint"
NEXT_PUBLIC_USDC_CONTRACT_ADDRESS = "0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238"
NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID = "2056cd0f53ff3372b3b40ad4c0508c44"
NEXT_PUBLIC_DASHBOARD_URL = "https://dash.staging.intuipay.xyz"
NEXT_PUBLIC_ASSET_DOMAIN = "https://assets.intuipay.xyz"
