"use client"

import { useState } from "react"
import Image from "next/image"
import { SiteHeader } from "@/components/site-header"
import { SiteFooter } from "@/components/site-footer"
import { ProjectCard } from "@/components/project-card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu"
import { Search, SlidersHorizontal, ArrowUpDown, ChevronDown } from "lucide-react"
import { FilterDrawer } from "@/components/filter-drawer"

const projects = [
  {
    id: "1",
    slug: "neurobridge", // Added slug, matches detail page mock
    title: "NeuroBridge",
    description: "Bridging Brain Health and AI for Early Alzheimer's Detection and Intervention Strategies.",
    universityName: "Emory University",
    imageUrl: "/abstract-brain-activity-digital-art-1.png",
    totalRaised: 1234567.0,
  },
  {
    id: "2",
    slug: "quantumleap-ai", // Added slug
    title: "QuantumLeap AI",
    description:
      "Developing next-generation AI algorithms using quantum computing principles for complex problem solving.",
    universityName: "ArtCenter College",
    imageUrl: "/placeholder-xg1ua.png",
    totalRaised: 876543.21,
  },
  {
    id: "3",
    slug: "biosynth-ethics", // Added slug
    title: "BioSynth Ethics",
    description: "Exploring the ethical implications of synthetic biology and AI in creating novel life forms.",
    universityName: "UCLA",
    imageUrl: "/placeholder-qtpze.png",
    totalRaised: 500000.0,
  },
  {
    id: "4",
    slug: "ai-climate-model", // Added slug
    title: "AI Climate Model",
    description: "Advanced AI modeling for predicting climate change impacts with higher accuracy.",
    universityName: "Stanford University",
    imageUrl: "/abstract-climate-change-ai-model-4.png",
    totalRaised: 750000.0,
  },
  {
    id: "5",
    slug: "robotic-surgery-ai", // Added slug
    title: "Robotic Surgery AI",
    description: "AI-powered precision enhancement for robotic surgical procedures.",
    universityName: "Johns Hopkins",
    imageUrl: "/placeholder-7jicc.png",
    totalRaised: 1100000.0,
  },
  {
    id: "6",
    slug: "ai-for-education", // Added slug
    title: "AI for Education",
    description: "Personalized learning paths generated by AI to improve educational outcomes.",
    universityName: "MIT",
    imageUrl: "/placeholder.svg?width=400&height=225",
    totalRaised: 600000.0,
  },
]

export default function ProjectsPage() {
  // Renamed component for clarity
  const [isFilterDrawerOpen, setIsFilterDrawerOpen] = useState(false)

  return (
    <div className="flex flex-col min-h-screen bg-neutral-white text-neutral-text">
      <SiteHeader />
      <main className="flex-grow">
        {/* Hero Section */}
        <section className="py-12 md:py-20 lg:py-28 bg-gradient-to-b from-intuipay-lighterblue/20 via-neutral-white to-neutral-white">
          <div className="container text-center">
            <h1 className="text-3xl sm:text-4xl md:text-5xl lg:text-6xl font-bold tracking-tight mb-6">
              Fuel Trusted University-Backed Research
            </h1>
            <p className="max-w-3xl mx-auto text-base sm:text-lg md:text-xl text-neutral-darkgray mb-10">
              All projects on Intuipay are verified academic research initiatives from accredited universities and
              institutions, ensuring every donation supports real, impactful science.
            </p>
            <div className="relative w-full max-w-5xl mx-auto aspect-[21/9] md:aspect-[24/9] sm:aspect-[16/9] lg:aspect-[21/9] rounded-lg overflow-hidden shadow-xl">
              <Image
                src="/hero-image.jpeg"
                alt="Stylized image of hands exchanging coins over a digital interface"
                fill
                priority
                className="object-cover"
                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 80vw, 1280px"
              />
            </div>
          </div>
        </section>

        {/* Search and Filter Section */}
        <section className="py-8 md:py-12">
          <div className="container">
            {/* Search Bar and Filter Button */}
            <div className="flex flex-col lg:flex-row gap-y-4 gap-x-0 lg:gap-x-4 lg:items-stretch mb-8">
              {/* Search Input Group */}
              <div className="flex w-full md:flex-grow max-w-xl mx-auto md:mx-0 md:max-w-none">
                <Input
                  type="search"
                  placeholder="Search"
                  className="rounded-r-none focus:ring-0 focus:border-neutral-mediumgray border-r-0 h-11 text-base bg-neutral-lightgray flex-grow"
                />
                <Button type="submit" className="bg-action-blue hover:bg-action-blue/90 rounded-l-none h-11 px-5">
                  <Search className="h-5 w-5 text-primary-foreground" />
                  <span className="sr-only">Search</span>
                </Button>
              </div>
              {/* Filter Button */}
              <div className="w-full md:w-auto">
                <Button
                  variant="outline"
                  className="w-full md:w-auto h-11 border-neutral-mediumgray text-base flex items-center justify-center"
                  onClick={() => setIsFilterDrawerOpen(true)}
                >
                  <SlidersHorizontal className="mr-2 h-4 w-4" />
                  Filter
                </Button>
              </div>
            </div>

            {/* Explore Projects Title and Sort By Dropdown */}
            <div className="flex flex-col space-y-4 lg:space-y-0 lg:flex-row justify-between items-center mb-6 md:mb-8">
              <h2 className="text-2xl sm:text-3xl font-semibold">
                Explore {projects.length * 100 + (projects.length % 3) * 10} Projects
              </h2>
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Button variant="outline" className="w-full lg:w-auto h-11 border-neutral-mediumgray text-base">
                    <ArrowUpDown className="mr-2 h-4 w-4" />
                    Newest
                    <ChevronDown className="ml-2 h-4 w-4" />
                  </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent align="end">
                  <DropdownMenuItem>Newest</DropdownMenuItem>
                  <DropdownMenuItem>Oldest</DropdownMenuItem>
                  <DropdownMenuItem>Most Raised</DropdownMenuItem>
                  <DropdownMenuItem>Ending Soon</DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 sm:gap-8">
              {projects.map((project) => (
                <ProjectCard key={project.id} project={project} />
              ))}
            </div>
          </div>
        </section>
      </main>
      <SiteFooter />
      <FilterDrawer isOpen={isFilterDrawerOpen} onOpenChange={setIsFilterDrawerOpen} />
    </div>
  )
}
